// ============================================
// ANTI-FRANGO - Mock Data
// All prices in BRL (R$)
// ============================================

const PRODUCTS = [
  // Camisetas Dry-fit
  {
    id: 'p001',
    name: 'Camiseta Dry-Fit Anti-Frango OG',
    category: 'camisetas',
    subcategory: 'dry-fit',
    gender: 'masculino',
    type: 'treino-pesado',
    price: 89.90,
    originalPrice: 109.90,
    discount: 18,
    rating: 4.8,
    reviews: 247,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
      'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=600&q=80',
    ],
    colors: ['#1A1A1A', '#FF6A00', '#FFFFFF', '#D11A1A'],
    sizes: ['P', 'M', 'G', 'GG', 'XGG'],
    badge: 'sale',
    description: 'Tecnologia Dry-Fit ultra leve que seca 3x mais rápido. Perfeita para os treinos mais intensos. Corte regular com gola redonda. Anti-odor e proteção UV50+.',
    tags: ['#AntiFrago', '#DryFit', '#Treino'],
    inStock: true,
    featured: true,
  },
  {
    id: 'p002',
    name: 'Regata Compressão Beast Mode',
    category: 'regatas',
    subcategory: 'compressao',
    gender: 'masculino',
    type: 'treino-pesado',
    price: 79.90,
    originalPrice: null,
    discount: 0,
    rating: 4.9,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    ],
    colors: ['#1A1A1A', '#FF6A00', '#2A2A2A'],
    sizes: ['P', 'M', 'G', 'GG'],
    badge: 'new',
    description: 'Regata de compressão para máxima performance. Tecido com tecnologia 4-way stretch que acompanha cada movimento. Ideal para musculação, crossfit e artes marciais.',
    tags: ['#BeastMode', '#Compressão', '#Gym'],
    inStock: true,
    featured: true,
  },
  {
    id: 'p003',
    name: 'Oversized Drop da Semana',
    category: 'camisetas',
    subcategory: 'oversized',
    gender: 'unissex',
    type: 'lifestyle',
    price: 119.90,
    originalPrice: 149.90,
    discount: 20,
    rating: 4.7,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
    ],
    colors: ['#1A1A1A', '#F3E6D6', '#FFFFFF', '#FF6A00'],
    sizes: ['P', 'M', 'G', 'GG', 'XGG'],
    badge: 'drop',
    description: 'A oversized mais comentada da temporada. Caimento perfeito, algodão premium 100% combed. Estampa exclusiva Anti-Frango Gang na frente e costas.',
    tags: ['#Oversized', '#AntiFragoGang', '#Drop'],
    inStock: true,
    featured: true,
  },
  {
    id: 'p004',
    name: 'Shorts Treino Intenso',
    category: 'shorts',
    subcategory: 'treino',
    gender: 'masculino',
    type: 'treino-pesado',
    price: 99.90,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=600&q=80',
    ],
    colors: ['#1A1A1A', '#FF6A00', '#2A2A2A', '#FFFFFF'],
    sizes: ['P', 'M', 'G', 'GG'],
    badge: 'new',
    description: 'Short com bolso zipado, elástico ajustável e forro interno. Tecido microporoso que elimina o suor rapidamente. Perfeito para qualquer modalidade.',
    tags: ['#Shorts', '#Treino', '#CrossFit'],
    inStock: true,
    featured: false,
  },
  {
    id: 'p005',
    name: 'Boné Trucker Anti-Frango',
    category: 'bones',
    subcategory: 'trucker',
    gender: 'unissex',
    type: 'lifestyle',
    price: 59.90,
    originalPrice: 79.90,
    discount: 25,
    rating: 4.8,
    reviews: 201,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80',
    ],
    colors: ['#1A1A1A', '#FF6A00', '#D11A1A'],
    sizes: ['Único'],
    badge: 'sale',
    description: 'Boné trucker com tela respirável e aba reta. Bordado exclusivo Anti-Frango na frente. Ajuste snapback universal. Stilo na academia e na rua.',
    tags: ['#Boné', '#Trucker', '#Lifestyle'],
    inStock: true,
    featured: false,
  },
  {
    id: 'p006',
    name: 'Camiseta Feminina Fire',
    category: 'camisetas',
    subcategory: 'dry-fit',
    gender: 'feminino',
    type: 'treino-pesado',
    price: 89.90,
    originalPrice: null,
    discount: 0,
    rating: 4.9,
    reviews: 278,
    image: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=600&q=80',
    ],
    colors: ['#FF6A00', '#1A1A1A', '#D11A1A', '#FFFFFF'],
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    badge: 'new',
    description: 'Camiseta feminina com corte slim flattering. Dry-fit de alta performance com detalhes reflexivos para treinos noturnos. Proteção UV50+ e antiodor.',
    tags: ['#Feminino', '#Fire', '#GirlsWhoLift'],
    inStock: true,
    featured: true,
  },
  {
    id: 'p007',
    name: 'Legging Cardio Power',
    category: 'shorts',
    subcategory: 'legging',
    gender: 'feminino',
    type: 'cardio',
    price: 129.90,
    originalPrice: 159.90,
    discount: 19,
    rating: 4.7,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80',
    ],
    colors: ['#1A1A1A', '#FF6A00', '#7C3AED'],
    sizes: ['PP', 'P', 'M', 'G', 'GG'],
    badge: 'sale',
    description: 'Legging de cintura alta com cós largo antiderrapante. Tecido 4D Stretch com compressão moderada. Pocket lateral e bolso traseiro com zíper.',
    tags: ['#Legging', '#Cardio', '#Feminino'],
    inStock: true,
    featured: false,
  },
  {
    id: 'p008',
    name: 'Camiseta Lifestyle Gang',
    category: 'camisetas',
    subcategory: 'lifestyle',
    gender: 'unissex',
    type: 'lifestyle',
    price: 79.90,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=400&q=80',
    images: [
      'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&q=80',
    ],
    colors: ['#FFFFFF', '#1A1A1A', '#F3E6D6'],
    sizes: ['P', 'M', 'G', 'GG', 'XGG'],
    badge: null,
    description: 'Camiseta lifestyle em algodão pima 100% importado. Logo Anti-Frango bordado no peito. Perfeita para o dia a dia pós-treino. Lavagem pode ser feita na máquina.',
    tags: ['#Lifestyle', '#Gang', '#StreetWear'],
    inStock: true,
    featured: false,
  },
];

const BANNERS = [
  {
    id: 'b001',
    tag: '🔥 Drop da Semana',
    title: 'Oversized\nGang Edition',
    subtitle: 'Novo lançamento exclusivo Anti-Frango',
    btnText: 'Ver agora',
    productId: 'p003',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
    bgGradient: 'linear-gradient(135deg, #FF6A00 0%, #D11A1A 100%)',
  },
  {
    id: 'b002',
    tag: '⚡ Oferta Especial',
    title: 'Boné Trucker\n-25% OFF',
    subtitle: 'Por tempo limitado. Corra!',
    btnText: 'Aproveitar',
    productId: 'p005',
    image: 'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=600&q=80',
    bgGradient: 'linear-gradient(135deg, #7C3AED 0%, #FF6A00 100%)',
  },
  {
    id: 'b003',
    tag: '👑 Lançamento',
    title: 'Coleção\nFeminina Fire',
    subtitle: 'Para quem não brinca na academia',
    btnText: 'Explorar',
    productId: 'p006',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80',
    bgGradient: 'linear-gradient(135deg, #D11A1A 0%, #FF6A00 100%)',
  },
];

const COMMUNITY_POSTS = [
  {
    id: 'cp001',
    username: 'rodrigo_pesado',
    displayName: 'Rodrigo Pesado',
    avatar: 'https://i.pravatar.cc/80?img=11',
    level: 'Avançado',
    time: '2h atrás',
    caption: 'Dia de PR no supino! 120kg clean 🔥 Camiseta Anti-Frango deu sorte demais hoje. Já estou no modo ANTI-FRANGO total!',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    likes: 847,
    comments: 63,
    tags: ['#PRdia', '#SupernoVerde', '#AntiFrago'],
    liked: false,
    following: false,
  },
  {
    id: 'cp002',
    username: 'jessica_lifts',
    displayName: 'Jéssica Lifts',
    avatar: 'https://i.pravatar.cc/80?img=25',
    level: 'Avançado',
    time: '4h atrás',
    caption: 'Treino de perna completo hoje! 🦵 5 exercícios, 4 séries cada. Quem é de perna que curte! Usando a legging nova Anti-Frango e AMEI o caimento. Muita compressão e conforto.',
    image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500&q=80',
    likes: 1203,
    comments: 92,
    tags: ['#LegDay', '#GirlsWhoLift', '#AntiFragoGirl'],
    liked: true,
    following: true,
  },
  {
    id: 'cp003',
    username: 'marcos_beast',
    displayName: 'Marcos Beast',
    avatar: 'https://i.pravatar.cc/80?img=33',
    level: 'Intermediário',
    time: '6h atrás',
    caption: 'Crossfit de manhã cedo é vida! 💪 Não tem desculpa quando você tem uma marca que acredita no seu grind. Shoutout pra Anti-Frango pela regata INCRÍVEL!',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&q=80',
    likes: 534,
    comments: 28,
    tags: ['#CrossFit', '#MorningGrind', '#BeastMode'],
    liked: false,
    following: false,
  },
  {
    id: 'cp004',
    username: 'ana_cardio',
    displayName: 'Ana Cardio',
    avatar: 'https://i.pravatar.cc/80?img=47',
    level: 'Iniciante',
    time: '8h atrás',
    caption: 'Primeiro mês de treino completo! Sem faltar um dia sequer. Do iniciante ao... ainda iniciante mas com mais determinação 😂 Comprei minha primeira peça Anti-Frango e me sinto outra pessoa!',
    image: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=500&q=80',
    likes: 2341,
    comments: 187,
    tags: ['#Iniciante', '#Consistência', '#JornadaFit'],
    liked: false,
    following: false,
  },
  {
    id: 'cp005',
    username: 'thunder_paulo',
    displayName: 'Thunder Paulo',
    avatar: 'https://i.pravatar.cc/80?img=65',
    level: 'Avançado',
    time: '12h atrás',
    caption: 'Sessão de posing pra competição no fim do mês. 3 meses de prep e chegando firme! Usando a camiseta OG Anti-Frango nas fotos de comparação. A marca tá com tudo!',
    image: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=500&q=80',
    likes: 3876,
    comments: 241,
    tags: ['#Fisiculturismo', '#Prep', '#Bodybuilding'],
    liked: true,
    following: true,
  },
];

const ORDERS = [
  {
    id: 'ORD-2024-001',
    date: '10 Jan 2025',
    products: ['Camiseta Dry-Fit OG (M, Preto)'],
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=100&q=80',
    total: 89.90,
    status: 'delivered',
    statusLabel: 'Entregue',
    trackingCode: 'BR123456789BR',
  },
  {
    id: 'ORD-2024-002',
    date: '02 Fev 2025',
    products: ['Boné Trucker (Único, Preto)', 'Shorts Treino (G, Laranja)'],
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=100&q=80',
    total: 159.80,
    status: 'delivered',
    statusLabel: 'Entregue',
    trackingCode: 'BR987654321BR',
  },
  {
    id: 'ORD-2025-003',
    date: '15 Mar 2025',
    products: ['Oversized Gang Edition (GG, Preto)'],
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=100&q=80',
    total: 119.90,
    status: 'shipped',
    statusLabel: 'Enviado',
    trackingCode: 'BR456789123BR',
  },
  {
    id: 'ORD-2025-004',
    date: '08 Abr 2025',
    products: ['Regata Beast Mode (M, Preto)', 'Customização Personalizada'],
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100&q=80',
    total: 169.80,
    status: 'processing',
    statusLabel: 'Processando',
    trackingCode: null,
  },
];

const FEED_POSTS = [
  {
    id: 'fp001',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&q=80',
    username: 'rodrigo_pesado',
    likes: 847,
  },
  {
    id: 'fp002',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=300&q=80',
    username: 'jessica_lifts',
    likes: 1203,
  },
  {
    id: 'fp003',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=300&q=80',
    username: 'marcos_beast',
    likes: 534,
  },
  {
    id: 'fp004',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=300&q=80',
    username: 'thunder_paulo',
    likes: 3876,
  },
  {
    id: 'fp005',
    image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=300&q=80',
    username: 'ana_cardio',
    likes: 2341,
  },
  {
    id: 'fp006',
    image: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=300&q=80',
    username: 'carla_fitness',
    likes: 678,
  },
];

const CATEGORIES = [
  { id: 'todos', label: 'Todos', icon: 'fas fa-th' },
  { id: 'camisetas', label: 'Camisetas', icon: 'fas fa-tshirt' },
  { id: 'regatas', label: 'Regatas', icon: 'fas fa-swimmer' },
  { id: 'shorts', label: 'Shorts', icon: 'fas fa-male' },
  { id: 'bones', label: 'Bonés', icon: 'fas fa-hat-cowboy-side' },
];

const SHIRT_COLORS = [
  { hex: '#1A1A1A', label: 'Preto' },
  { hex: '#FFFFFF', label: 'Branco' },
  { hex: '#FF6A00', label: 'Laranja' },
  { hex: '#D11A1A', label: 'Vermelho' },
  { hex: '#7C3AED', label: 'Roxo' },
  { hex: '#1E40AF', label: 'Azul' },
  { hex: '#065F46', label: 'Verde' },
  { hex: '#F3E6D6', label: 'Creme' },
];

const MOTIVATIONAL_PHRASES = [
  'Anti-Frango Mode',
  'No Pain No Gain',
  'Projeto Verão 2026',
  'Beast Mode ON',
  'Modo Besteira OFF',
  'Não tem Frango',
  'Treino é Fé',
  'Seja Anti-Frango',
];

// Formatting utility
function formatPrice(price) {
  return `R$ ${price.toFixed(2).replace('.', ',')}`;
}

function formatPriceNum(price) {
  return price.toFixed(2).replace('.', ',');
}
